# Generated by Django 6.0.2 on 2026-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_text', models.CharField(max_length=200)),
                ('nepali_text', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('New', 'New'), ('Revision', 'Revision'), ('Mastered', 'Mastered')], default='New', max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
