# Generated by Django 6.0.2 on 2026-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='english_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
